#!/bin/bash
#Setting document root

if [ ! -d "$DOCUMENT_ROOT" ]; then
   echo "Creating document root folder $DOCUMENT_ROOT"
   mkdir -p "$DOCUMENT_ROOT"
else
   echo "Document root folder already exists, doing nothing."
fi

echo "Setting document root to $DOCUMENT_ROOT"
cp /etc/nginx/sites-enabled/site.conf /tmp
sed -i -e 's,root /var/www/html,root '"$DOCUMENT_ROOT"',g' /tmp/site.conf
cat /tmp/site.conf > /etc/nginx/sites-enabled/site.conf
